[build]
  command = "npm run build"
  publish = "build"

  node_version = "18.20.2"

[dev]
  command = "npm start"
  port = 3000

[template.environment]
  SUPABASE_URL = "https://ofkfygqrfenctzitigae.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ma2Z5Z3FyZmVuY3R6aXRpZ2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjgwMjcsImV4cCI6MjA3MzI0NDAyN30.-GFl3-IncJ7hno_LHE5jtCOe_HI07nxwiq3aaISHolo"

[[redirects]]
  from = "/validation-key.txt"
  to = "/validation-key.txt"
  status = 200

[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service.html"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
