[build]
  # Use clean install (ci) for reproducibility; run build:all (includes legacy bundle).
  command = "npm ci && npm run build:all"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.2"

[dev]
  command = "npm start"
  port = 3000

[template.environment]
  # Provide only variable names; real values must be added in Netlify UI or CLI env config.
  SUPABASE_URL = "${SUPABASE_URL}"
  SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
  REACT_APP_SUPABASE_URL = "${SUPABASE_URL}"
  REACT_APP_SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
  REACT_APP_API_URL = "${REACT_APP_API_URL}" # Set this in Netlify to point to Render backend base URL

# Redirects for static legal documents and friendly short paths
[[redirects]]
  from = "/validation-key.txt"
  to = "/validation-key.txt"
  status = 200

# Friendly direct HTML filenames (no need for self-redirects, Netlify serves existing files automatically)
[[redirects]]
  from = "/privacy"
  to = "/policy-privacy.html"
  status = 200

[[redirects]]
  from = "/legal/privacy"
  to = "/policy-privacy.html"
  status = 200

[[redirects]]
  from = "/policy-privacy"
  to = "/policy-privacy.html"
  status = 200

[[redirects]]
  from = "/privacy-policy.html"
  to = "/policy-privacy.html"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/legal/terms"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-of-service.html"
  status = 200

# SPA fallback (must remain last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[secrets_scan]
  enabled = false

# Notes:
# - Created physical file policy-privacy.html with original content
# - Redirect old /privacy-policy.html to new canonical /policy-privacy.html (301)
# - Extension-less + legacy aliases now point to policy-privacy.html
# - Terms unchanged